version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: jest
    versions:
    - "> 25.2.0"
  - dependency-name: "@nestjs/cli"
    versions:
    - "> 7.1.1, < 8"
  - dependency-name: ts-jest
    versions:
    - "> 25.2.1"
  - dependency-name: tslint
    versions:
    - "> 6.1.0, < 7"
  - dependency-name: "@types/express"
    versions:
    - "> 4.17.3, < 5"
  - dependency-name: "@types/jest"
    versions:
    - "> 25.1.4"
