version: '3.4'

services:
  metallum:
    image: hichuyamichu/metallum:latest
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - main
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
    

networks:
  main:
    external: true
