FROM node:12-alpine
WORKDIR /usr/src/metallum

COPY server/package.json server/package-lock.json server/tsconfig.json server/tsconfig.build.json ./

RUN npm install

COPY . .

RUN npm run build

ENV DATABASE_HOST= \
DATABASE_PORT= \
DATABASE_USER= \
DATABASE_PASS= \
DATABASE_NAME= 

EXPOSE 3000

CMD ["npm", "run", "start:prod"]