version: '3.4'

services:
  metallum:
    build: .
    restart: unless-stopped
    networks:
      - main
    env_file:
      - ./.env
    ports: 
      - "3000:3000"

networks:
  main:
    external: true
