  
FROM golang:latest AS build

WORKDIR /build

ENV GO111MODULE=on

COPY scraper/go.mod scraper/go.sum ./

RUN go mod download

COPY scraper ./

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o metallum .

FROM scratch

WORKDIR /app

COPY --from=build /build/metallum /app/

EXPOSE 7000

CMD ["./metallum", "listen"]