  
FROM golang:latest AS build

ENV GO111MODULE=on

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o metallum .

FROM scratch

WORKDIR /app

COPY --from=build /build/metallum /app/

EXPOSE 7000

CMD ["./metallum"]