FROM node:12-alpine
WORKDIR /usr/src/metallum

COPY package.json npm-lock.yaml tsconfig.json tsconfig.build.json ./
RUN apk add --no-cache --virtual .build-deps curl  \
&& npm install \
&& apk del .build-deps

COPY . .

RUN npm run build

ENV DB_HOST= \
DB_PORT= \
DB_USER= \
DB_PASSWORD= \
DB_NAME= 

EXPOSE 3000

CMD ["npm", "run", "start:prod"]